#!/usr/bin/env node

/**
 * Local Health Check Script
 * Generated by syntropic init.
 * Checks build, localhost refs, npm audit, git state.
 */

const { execSync } = require('child_process');
const https = require('https');

async function checkResponseTime(url) {
  return new Promise((resolve) => {
    const start = Date.now();
    https.get(url, { timeout: 10000 }, (res) => {
      resolve({ status: res.statusCode, time: Date.now() - start });
    }).on('error', () => {
      resolve({ status: 0, time: null });
    });
  });
}

async function runNpmAudit() {
  try {
    const { stdout } = require('child_process').execSync('npm audit --json', { encoding: 'utf8' });
    const audit = JSON.parse(stdout);
    return audit.metadata?.vulnerabilities || {};
  } catch (error) {
    if (error.stdout) {
      try {
        return JSON.parse(error.stdout).metadata?.vulnerabilities || {};
      } catch {}
    }
    return {};
  }
}

async function run() {
  console.log('Running health check...\n');

  // npm audit
  const vulns = await runNpmAudit();
  console.log('npm audit:', vulns.total ? `${vulns.total} vulnerabilities (${vulns.critical || 0} critical)` : 'Clean');

  // Build check
  try {
    execSync('npm run build', { stdio: 'pipe', timeout: 120000 });
    console.log('Build: PASS');
  } catch {
    console.log('Build: FAIL');
    process.exit(1);
  }

  console.log('\nHealth check complete.');
}

run().catch((err) => {
  console.error('Health check failed:', err.message);
  process.exit(1);
});
